import os
import glob
import argparse
import torch
import numpy as np
import matplotlib.pyplot as plt

class GridSearchVisualizer:
    """
    Ingests serialized tensors from the grid search execution, extracts the 2D manifold 
    embedded in the 3D ambient space, and renders high-resolution geometric comparisons.
    """
    def __init__(self, data_dir: str, out_dir: str):
        self.data_dir = data_dir
        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)

    def render_manifold_geometry(self, file_path: str):
        """
        Loads the tensor or dictionary, extracts the 3D coordinates, and serializes 
        the rendering to a PNG. Handles both raw coordinate tensors and structured dictionaries.
        """
        filename = os.path.basename(file_path)
        print(f"Processing grid search output: {filename}...")
        
        try:
            data = torch.load(file_path, map_location='cpu')
        except Exception as e:
            print(f"Failed to load {filename}: {e}")
            return

        # 1. Data Extraction Protocol
        original_X = None
        recon_X = None
        centers = None

        if isinstance(data, dict):
            # Assumes structured grid search output
            if 'original_ambient' in data:
                original_X = data['original_ambient'][:, :3].numpy()
            if 'reconstructed_ambient' in data:
                recon_X = data['reconstructed_ambient'][:, :3].numpy()
            if 'fps_centers' in data:
                centers = data['fps_centers'][:, :3].numpy()
        elif isinstance(data, torch.Tensor):
            # Assumes raw tensor output
            recon_X = data[:, :3].numpy()
        else:
            print(f"Unrecognized data structure in {filename}. Skipping.")
            return

        # 2. Rendering Execution
        has_comparison = original_X is not None and recon_X is not None
        fig = plt.figure(figsize=(16, 8) if has_comparison else (10, 8), dpi=300)

        if has_comparison:
            self._plot_3d_axis(fig, 121, original_X, "Original Ambient Data", None)
            self._plot_3d_axis(fig, 122, recon_X, f"Reconstructed Geometry: {filename}", centers)
        else:
            self._plot_3d_axis(fig, 111, recon_X, f"Manifold Geometry: {filename}", centers)

        # 3. Serialization
        out_filename = filename.replace('.pt', '_grid_render.png')
        out_path = os.path.join(self.out_dir, out_filename)
        
        plt.tight_layout()
        plt.savefig(out_path, format='png', bbox_inches='tight')
        plt.close(fig)
        
        print(f"Visualization serialized to: {out_path}")

    def _plot_3d_axis(self, fig, subplot_grid, X: np.ndarray, title: str, centers: np.ndarray = None):
        """
        Constructs the strict 3D scatter projection using the Z-axis coordinate 
        for the color channel to highlight extrinsic curvature.
        """
        ax = fig.add_subplot(subplot_grid, projection='3d')

        # Depth-sorting (Z-buffer) via Z-axis scalar
        z_scalars = X[:, 2]
        
        ax.scatter(
            X[:, 0], 
            X[:, 1], 
            X[:, 2], 
            c=z_scalars, 
            cmap='viridis', 
            s=2.0, 
            alpha=0.6,
            edgecolors='none'
        )

        # Overlay Whitney Atlas FPS Centers if available
        if centers is not None:
            ax.scatter(
                centers[:, 0], 
                centers[:, 1], 
                centers[:, 2], 
                c='red', 
                s=25.0, 
                marker='X',
                edgecolors='black',
                label='FPS Centers'
            )
            ax.legend(loc='upper right')

        ax.set_title(title, fontsize=12, pad=10)
        ax.set_xlabel("Ambient X_1")
        ax.set_ylabel("Ambient X_2")
        ax.set_zlabel("Ambient X_3")
        
        # Eliminate background panes to isolate manifold topology
        ax.xaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
        ax.yaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
        ax.zaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))

        # Enforce fixed viewing angle for objective comparisons across grid parameters
        ax.view_init(elev=30, azim=45)

def main():
    parser = argparse.ArgumentParser(description="Render 3D topological geometries from grid search tensors.")
    parser.add_argument('--data_dir', type=str, default='grid_search_outputs', help='Directory containing the grid search .pt files')
    parser.add_argument('--out_dir', type=str, default='grid_visualizations', help='Directory for serialized PNGs')
    args = parser.parse_args()

    visualizer = GridSearchVisualizer(args.data_dir, args.out_dir)

    # Ingest all tensor files generated by the grid search
    target_files = glob.glob(os.path.join(args.data_dir, "*.pt"))
    
    if not target_files:
        print(f"No .pt files located in {args.data_dir}.")
        return

    for file_path in target_files:
        visualizer.render_manifold_geometry(file_path)

if __name__ == "__main__":
    main()