import os
import argparse
import torch
import matplotlib.pyplot as plt

class TopologicalVisualizer:
    """
    Ingests ambient manifold tensors and generates direct 3D visualizations 
    of the spatial coordinates without density estimation.
    """
    def __init__(self, data_dir: str, out_dir: str):
        self.data_dir = data_dir
        self.out_dir = out_dir
        os.makedirs(self.out_dir, exist_ok=True)

    def render_plot(self, tensor_filename: str):
        """
        Loads the specified tensor and serializes the 3D scatter plot as a high-resolution PNG.
        """
        file_path = os.path.join(self.data_dir, tensor_filename)
        if not os.path.exists(file_path):
            print(f"File not found: {file_path}. Skipping.")
            return

        print(f"Processing tensor: {tensor_filename}...")
        
        # 1. Ingestion and Dimensionality Truncation
        tensor = torch.load(file_path, map_location='cpu')
        
        if isinstance(tensor, dict) and 'atlas_frames' in tensor:
            print(f"Skipping {tensor_filename}: Contains frozen geometry dictionary, not ambient coordinates.")
            return
            
        X = tensor[:, :3].numpy()

        # 2. 3D Rendering Protocol (Color mapped directly to the Z-axis coordinate)
        fig = plt.figure(figsize=(10, 8), dpi=300)
        ax = fig.add_subplot(111, projection='3d')

        scatter = ax.scatter(
            X[:, 0], 
            X[:, 1], 
            X[:, 2],  
            s=5.0, 
            alpha=0.8,
            edgecolors='none'
        )

        ax.set_title(f"Manifold Geometry: {tensor_filename}", fontsize=14, pad=15)
        ax.set_xlabel("Ambient X_1")
        ax.set_ylabel("Ambient X_2")
        ax.set_zlabel("Ambient X_3")
        
        # Transparent background for strict data focus
        ax.xaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
        ax.yaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))
        ax.zaxis.set_pane_color((1.0, 1.0, 1.0, 0.0))


        # 3. Serialization
        out_filename = tensor_filename.replace('.pt', '_geometry.png')
        out_path = os.path.join(self.out_dir, out_filename)
        
        plt.tight_layout()
        plt.savefig(out_path, format='png', bbox_inches='tight')
        plt.close(fig)
        
        print(f"Visualization serialized to: {out_path}")

def main():
    parser = argparse.ArgumentParser(description="Render empirical density maps of the ambient manifolds.")
    parser.add_argument('--data_dir', type=str, default='../generative_model_arch/data/raw', help='Directory containing the .pt tensors')
    parser.add_argument('--out_dir', type=str, default='../generative_model_arch/data/visualizations', help='Directory for serialized PNGs')
    args = parser.parse_args()

    visualizer = TopologicalVisualizer(args.data_dir, args.out_dir)

    # Standard temporal states generated by 00_generate_manifolds.py
    target_tensors = [
        "dataset.pt",
    ]

    for tensor_file in target_tensors:
        visualizer.render_plot(tensor_file)

if __name__ == "__main__":
    main()